### ISSUE TITLE
uwu wots is thnis

### ISSUE THREAD

**Issue by Sardonyx78** [VelvetThePanda/e621-downloader#1]
title explains

**Comment by VelvetThePanda** [comment]
https://cdn.discordapp.com/emojis/362554149595906048.png

**Comment by NatsumiHB** [comment]
GO AWAY WHILE YOU STILL CAN

THE LANDS OF E621 ARENT MADE FOR YOUR PURE SOUL

**Comment by Sardonyx78** [comment]
> GO AWAY WHILE YOU STILL CAN
> 
> THE LANDS OF E621 ARENT MADE FOR YOUR PURE SOUL

summer-chan shush

**Comment by NatsumiHB** [comment]
> 
> 
> > GO AWAY WHILE YOU STILL CAN
> > THE LANDS OF E621 ARENT MADE FOR YOUR PURE SOUL
> 
> summer-chan shush

no u uwu

**Comment by Sardonyx78** [comment]
> > 
> > 
> > > GO AWAY WHILE YOU STILL CAN
> > > THE LANDS OF E621 ARENT MADE FOR YOUR PURE SOUL
> > 
> > summer-chan shush
> 
> no u uwu

omg u so qt

**Comment by NatsumiHB** [comment]
> 
> 
> > > > GO AWAY WHILE YOU STILL CAN
> > > > THE LANDS OF E621 ARENT MADE FOR YOUR PURE SOUL
> > > 
> > > 
> > > summer-chan shush
> > 
> > 
> > no u uwu
> 
> omg u so qt

no u owo

**Comment by Sardonyx78** [comment]
> > > > > GO AWAY WHILE YOU STILL CAN
> > > > > THE LANDS OF E621 ARENT MADE FOR YOUR PURE SOUL
> > > > 
> > > > 
> > > > summer-chan shush
> > > 
> > > 
> > > no u uwu
> > 
> > 
> > omg u so qt
> 
> no u owo

lol ily

**Comment by NatsumiHB** [comment]
wow rude destroying our wholesome love like this smh my head time to #CancelVelvet

**Comment by Symbxlz** [comment]
let love happen smh

**Comment by Symbxlz** [comment]
oh this is my old username how do i change :(

**Comment by NatsumiHB** [comment]
> 
> 
> oh this is my old username how do i change :(

You don't, you're stuck with this now :c

**Comment by Symbxlz** [comment]
i wanw cwuddles 😞

**Comment by Sardonyx78** [comment]
OMG RE OPEN THIS #CancelVelvet

**Comment by NatsumiHB** [comment]
> 
> 
> i wanw cwuddles 😞

mood :c

**Comment by NatsumiHB** [comment]
velvet won't open this again but our love stands strong

**Comment by Symbxlz** [comment]
c-cwan i j-join 😦

**Comment by NatsumiHB** [comment]
always
